services:
    bizbink.sociallinks.listener:
        class: bizbink\sociallinks\event\main_listener
        arguments:
            - @config
            - @template
        tags:
            - { name: event.listener }
